CREATE TABLE IF NOT EXISTS `portal_links` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `link_key` VARCHAR(100) NOT NULL,
    `tab_name` VARCHAR(100) NOT NULL,
    `name` VARCHAR(150) NOT NULL,
    `url` VARCHAR(2048) NOT NULL,
    `icon` VARCHAR(80) NOT NULL DEFAULT 'apps_outlined',
    `color` VARCHAR(20) NOT NULL DEFAULT '#0284C7',
    `image_path` VARCHAR(500) NULL,
    `sort_order` INT NOT NULL DEFAULT 0,
    `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_portal_links_key` (`link_key`),
    KEY `idx_portal_links_active_order` (`is_active`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `portal_links` (`link_key`, `tab_name`, `name`, `url`, `icon`, `color`, `sort_order`) VALUES
('abi.trust', 'Abi Portal', 'TRUST', 'http://103.156.171.71/TRUST/login.php', 'verified_user_outlined', '#DC2626', 1),
('abi.overall_accounts', 'Abi Portal', 'Overall Accounts', 'https://account.arminfo.in/', 'account_balance_wallet_outlined', '#0891B2', 2),
('abi.mfi', 'Abi Portal', 'MFI', 'http://103.156.171.71/MFI/login.php', 'savings_outlined', '#CA8A04', 3),
('abi.hanniji', 'Abi Portal', 'HANNIJI', 'http://103.156.171.71/HANNIJI/login.php', 'apps', '#6366F1', 4),
('abi.aura', 'Abi Portal', 'AURA', 'http://103.156.171.71/AURA/login.php', 'apps', '#0EA5E9', 5),
('abi.employment', 'Abi Portal', 'Employment', 'http://150.242.202.172/employment/login.php', 'work_outline', '#16A34A', 6),
('abi.ornaments', 'Abi Portal', 'Ornaments', 'http://150.242.202.172/ORNAMENTS/login.php', 'diamond_outlined', '#D97706', 7),
('abi.enterprises', 'Abi Portal', 'Enterprises', 'http://150.242.202.172/enterprices/login.php', 'business_outlined', '#8B5CF6', 8),
('abi.veyon_agency', 'Abi Portal', 'Veyon Agency', 'https://veyonag.arminfo.in/login.php', 'groups_outlined', '#EC4899', 9),
('abi.veyon_global', 'Abi Portal', 'Veyon Global', 'https://veyongb.arminfo.in/login.php', 'public_outlined', '#14B8A6', 10),
('abi.hardware', 'Abi Portal', 'Hardware', 'http://103.156.171.71/hardware/login.php', 'developer_board_outlined', '#475569', 11),
('kavi_manju.karumandapam', 'Kavi Manju Portal', 'Karumandapam', 'http://103.156.171.71/fund_nidhi/login.php', 'savings_outlined', '#0D9488', 12),
('kavi_manju.neyveli', 'Kavi Manju Portal', 'Neyveli', 'http://103.156.171.71/nidhi/login.php', 'account_balance_outlined', '#2563EB', 13),
('kavi_manju.karaikudi', 'Kavi Manju Portal', 'Karaikudi', 'http://103.156.171.71/mahesan_nidhi/login.php', 'account_balance_outlined', '#7C3AED', 14),
('kavi_manju.nidhi_rd', 'Kavi Manju Portal', 'Nidhi RD', 'http://103.156.171.71/NIDHI_RD/login.php', 'repeat_outlined', '#059669', 15),
('kavi_manju.smb_matriculation', 'Kavi Manju Portal', 'SMB Matriculation', 'http://150.242.202.172/smbschool/loginpage.php', 'school_outlined', '#2563EB', 16),
('kavi_manju.smb_nursery', 'Kavi Manju Portal', 'SMB Nursery', 'http://150.242.202.172/smbnursery/loginpage.php', 'child_care_outlined', '#06B6D4', 17),
('kavi_manju.infotech', 'Kavi Manju Portal', 'Infotech', 'http://150.242.202.172/Infotech/login.php', 'computer_outlined', '#EC4899', 18),
('kavi_manju.mahesan_gl', 'Kavi Manju Portal', 'Mahesan GL', 'http://103.207.3.66/mahesangl/login.php', 'groups_outlined', '#7C2D12', 19),
('kavi_manju.armss_gl', 'Kavi Manju Portal', 'ARMSS GL', 'http://103.207.3.66/armssgl/login.php', 'groups_outlined', '#1D4ED8', 20),
('kavi_manju.mcf', 'Kavi Manju Portal', 'MCF', 'https://mcf.arminfo.in/', 'corporate_fare_outlined', '#B91C1C', 21),
('kavi_manju.mis', 'Kavi Manju Portal', 'MIS', 'http://mis.arminfo.in/', 'dashboard_outlined', '#334155', 22),
('vetri.veyon_stationery', 'Vetri Portal', 'Veyon Stationery Management', 'https://veyon.arminfo.in/', 'inventory_2_outlined', '#0284C7', 23),
('vetri.trust', 'Vetri Portal', 'Trust', 'https://trust.arminfo.in/', 'account_balance_outlined', '#F97316', 24),
('dinesh.payroll', 'Dinesh Portal', 'Payroll', 'http://103.156.171.71/payroll/public/index.php', 'payments_outlined', '#15803D', 25)
ON DUPLICATE KEY UPDATE `link_key` = VALUES(`link_key`);
